"""add_stock_data_freshness

Revision ID: 189a2adad7f3
Revises: 06281f950a18
Create Date: 2026-05-30 14:51:20.651228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189a2adad7f3'
down_revision: Union[str, Sequence[str], None] = '06281f950a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('last_price_update', sa.DateTime(), nullable=True))
    op.add_column('stocks', sa.Column('data_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'data_source')
    op.drop_column('stocks', 'last_price_update')
    # ### end Alembic commands ###
